exception_handling_p2.py